const azerbaijaniBadWords = [
  // Single words
  'sik', 'siki', 'sikil', 'sikin', 'sikib', 'sikiş', 'sikmək',
  'sikən', 'sikəyim', 'sikdirməyim',
  'göt', 'götü', 'götün', 'götveren', 'götqulağı',
  'amcıq', 'amciq', 'amına', 'amını',
  'orospu', 'orospuluq',
  'fahişə', 'fahishe', 'fahişəlik',
  'piç', 'pic', 'piçlik',
  'eşşək', 'essek',
  'qancıq', 'qanciq',
  'heyvan', 'heyvanlıq',
  'məlun', 'melun',
  'lənət', 'lenat',
  'murdar',
  'alçaq', 'alcaq',
  'rəzil', 'rezil',
  'namussuz',
  'həyasız', 'heyasiz',
  'kəsəyim', 'keseyim',
  'bok', 'boka', 'bokun',
  'sidiyi', 'sidik',
  'qıç', 'dəlik', 'delik',
  'kus', 'küs',
  'sürtük', 'surtuk', 'sürtüklük',
  'pozğun', 'pozgun',
  'azğın', 'azgin',
  'cındır', 'cindir',
  'öldürəcəm', 'oldurecem',
  'gebertəcəm', 'gebertecem',
  'döyəcəm', 'doyecem',
  'parçalayacam',
  'yandıraram', 'yandiraram',
  'kəsərəm', 'keserem',
  'axmaq', 'axmaqsın', 'axmaqlıq',
  'gic', 'giclik',
  'köpək', 'kopek',
  'qaşar', 'qaşarlıq',
  // Phrases (handled separately in wordFilter.js)
  'orospu balası', 'orospu uşağı',
  'piç balası', 'it oğlu', 'itoğlu',
  'eşşəyin balası', 'köpək balası',
  'get cəhənnəmə', 'get cehenneme',
  'rədd ol', 'redd ol',
  'bok ye', 'sus it',
  'lənətullaha',
];

export default azerbaijaniBadWords;